if: 'branch =~ ^master$|^development$'
jobs:
  include:
    - stage: changelog
      script:
        - ./changelog.sh
      if: 'branch = master AND type != pull_request AND !(commit_message =~ /(\[skip changelog\])/)'
